"""更新用户模型

Revision ID: 3495bdcb2c7b
Revises: 4c2e0b2ef973
Create Date: 2023-09-01 14:29:41.441262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3495bdcb2c7b'
down_revision = '4c2e0b2ef973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
